language: clojure
lein: lein
script: lein midje
jdk:
  - openjdk8
  - openjdk11
  - oraclejdk11
after_success:
  - CLOVERAGE_VERSION=1.1.2 lein cloverage --codecov --runner :midje
  - bash <(curl -s https://codecov.io/bash)
